name: Update Project Stats
on:
  schedule:
    - cron: '0 6 * * *' # Run daily at 6 AM UTC
  workflow_dispatch: # Allow manual trigger
  push:
    branches: [ main ]

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Generate Project Cards
        run: |
          cat > generate-cards.js << 'EOF'
          const fs = require('fs');
          
          // Project configuration - you can add/remove projects here
          const projects = [
            {
              name: "Alterion-lang",
              repo: "Chace-Berry/Alterion-lang",
              description: "A modern, expressive programming language for native, web, and mobile apps.",
              logoLight: "https://raw.githubusercontent.com/Chace-Berry/Alterion-lang/main/assets/Logo_Dark.svg?v=1",
              logoDark: "https://raw.githubusercontent.com/Chace-Berry/Alterion-lang/main/assets/Logo.svg?v=1"
            }
          ];
          
          async function fetchRepoStats(repo) {
            try {
              const response = await fetch(`https://api.github.com/repos/${repo}`, {
                headers: {
                  'User-Agent': 'GitHub-Action'
                }
              });
              if (!response.ok) {
                throw new Error(`HTTP ${response.status}`);
              }
              const data = await response.json();
              return {
                stars: data.stargazers_count || 0,
                forks: data.forks_count || 0,
                language: data.language || 'Unknown'
              };
            } catch (error) {
              console.error(`Error fetching stats for ${repo}:`, error);
              return { stars: 0, forks: 0, language: 'Unknown' };
            }
          }
          
          async function generateCards() {
            let cardsHtml = '';
            
            for (const project of projects) {
              const stats = await fetchRepoStats(project.repo);
              
              const cardHtml = `
          <div style="max-width: 800px; margin: 20px auto; border-radius: 30px; overflow: hidden; box-shadow: 0 4px 20px rgba(0,0,0,0.15); display: flex; height: 250px;">
            <!-- Left side - Logo area -->
            <div style="flex: 0 0 200px; background: linear-gradient(135deg, #1a1a1a 0%, #0d1117 100%); display: flex; align-items: center; justify-content: center; position: relative;">
              <div style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); width: 80px; height: 80px; border-radius: 50%; background: radial-gradient(circle, rgba(58, 123, 213, 0.3) 0%, transparent 70%);"></div>
              <a href="https://github.com/${project.repo}" target="_blank" style="text-decoration: none; z-index: 1;">
                <picture>
                  <source media="(prefers-color-scheme: dark)" srcset="${project.logoDark}">
                  <source media="(prefers-color-scheme: light)" srcset="${project.logoLight}">
                  <img alt="${project.name} Logo" src="${project.logoLight}" width="60" style="display: block; margin: auto; position: relative; z-index: 2;">
                </picture>
              </a>
            </div>
            
            <!-- Right side - Info area -->
            <div style="flex: 1; background: linear-gradient(135deg, #4a4a4a 0%, #2d2d2d 100%); color: white; padding: 30px 25px; display: flex; flex-direction: column; justify-content: space-between; position: relative;">
              <!-- Content -->
              <div>
                <h3 style="margin: 0 0 8px 0; font-size: 24px; font-weight: 700; color: #ffffff; letter-spacing: -0.5px;">${project.name}</h3>
                <p style="margin: 0 0 15px 0; font-size: 14px; line-height: 1.4; color: #c9d1d9; opacity: 0.9;">${project.description}</p>
              </div>
              
              <!-- Stats badges at bottom -->
              <div style="display: flex; gap: 8px; align-items: center;">
                <img src="https://img.shields.io/github/stars/${project.repo}?style=for-the-badge&logo=github&logoColor=white&color=58a6ff&labelColor=rgba(255,255,255,0.1)" alt="GitHub stars">
                <img src="https://img.shields.io/github/forks/${project.repo}?style=for-the-badge&logo=github&logoColor=white&color=58a6ff&labelColor=rgba(255,255,255,0.1)" alt="GitHub forks">
              </div>
            </div>
          </div>`;
              
              cardsHtml += cardHtml;
            }
            
            return cardsHtml;
          }
          
          generateCards().then(cards => {
            const readmeContent = fs.readFileSync('README.md', 'utf8');
            const updatedContent = readmeContent.replace(
              /<!-- PROJECT_CARDS_START -->[\s\S]*?<!-- PROJECT_CARDS_END -->/,
              `<!-- PROJECT_CARDS_START -->\n${cards}\n<!-- PROJECT_CARDS_END -->`
            );
            fs.writeFileSync('README.md', updatedContent);
            console.log('Project cards updated successfully!');
          });
          EOF
          
          node generate-cards.js
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --staged --quiet || git commit -m "Update project stats"
          git push
